### PR TITLE
Adding PasswordInput widget

### LINKED ISSUE #792: Password input widget
The password input widget will be an opinionated constrained-input with `type: password`.

Inappropriate properties should not be exposed.

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

Adding password input widget, `PasswordInput`.  Is a regular `ConstrainedInput` widget but with a set type of `password` and a toggle button to see the password.

Resolves #792 

image

image

### CODE REVIEW

**Comment by rorticus** [comment]
Oops! Yeah probably. Good catch!

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-rw7wm3znp.now.sh
* Tests Deployment: https://dojowidgets-8amefpxxa.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-iu1xh6q1o.now.sh
* Tests Deployment: https://dojowidgets-4cj14utd8.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-f94i64qzb.now.sh
* Tests Deployment: https://dojowidgets-rkwr4b7k9.now.sh

**Pull request merged**
