### PR TITLE
Updating Dialog widget

### LINKED ISSUE #982: Update Dialog widget to use typed children
**Enhancement** 

Update the `Dialog` widget to use typed children support from Dojo 7. Usage would look something along the lines of,

```tsx
<Dialog closeable>
{{
    title: () => "Some title",
    content: () => "Some content"
}}
</Dialog>
```

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

Rewritten Dialog widget!  I'm submitting this as-is for now, we can either accept it and update it as the things mentioned under "caveats" below come in, or keep this around and keep updating it.

### New and improved

- Rewritten to be a functional widget
- Simplified properties
- Uses typed children for title / content
- Improved a11y on `alertdialog` role
- Removed animation properties, use themeing to change animations!
- Added animation example widget
- Moved the widget to the body tag and added `inert` middleware to trap focus to open modals
- Added "actions"

#### Material Themed Actions
image

#### Focus Trapped Inputs

Resolves #982

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-44p9hy29s.now.sh
* Tests Deployment: https://dojowidgets-k0xdpwmgc.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-9e4th3zlk.now.sh
* Tests Deployment: https://dojowidgets-7p69fc4zg.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-nr73bzdj3.now.sh
* Tests Deployment: https://dojowidgets-7glkv6lwu.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-gupqqi1b3.now.sh
* Tests Deployment: https://dojowidgets-nlb1xr7rh.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-fn3s2cuyo.now.sh
* Tests Deployment: https://dojowidgets-5xnmijdy3.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-59kra4b67.now.sh
* Tests Deployment: https://dojowidgets-1s6zsa9hz.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-59kra4b67.now.sh
* Tests Deployment: https://dojowidgets-1s6zsa9hz.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-59kra4b67.now.sh
* Tests Deployment: https://dojowidgets-1s6zsa9hz.now.sh

**Comment by tomdye** [comment]
This will need bodyScroll middleware added once https://github.com/dojo/widgets/pull/1024 has been merged

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-1y6c3x34c.now.sh
* Tests Deployment: https://dojowidgets-2jizn78yc.now.sh

**Comment by rorticus** [comment]
Fixed the exit animation! (with an update to dojo 7 alpha 7)

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-dm7bb48y5.now.sh
* Tests Deployment: https://dojowidgets-rcc3wcmee.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-dm7bb48y5.now.sh
* Tests Deployment: https://dojowidgets-37rsw28m2.now.sh

**Pull request merged**
