### PR TITLE
Email input

### LINKED ISSUE #789: Email input widget
The email input widget will essentially be a base `text-input` with opinionated default properties (such as `type: email`) and a subtly different styling. ie. an `@`/ `mail` icon symbol in the leading section of the input.

The email input should not expose properties such as `min` and `max` and others that do not apply to an email input. Native validation should work for email addresses.

This will expand our widget suite and allow a quick and consistently validated email input for use in dojo applications.

### PR DESCRIPTION
**Pull request by samenz**
**Type:** Feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:** Adds simple email input widget. The email input removes the following text-input properties from it's interface:
- customValidator
- max
- min
- step
- onKeyDown
- onKeyUp
- pattern
- type

**Code Description:**
- Add email input widget
- Add email input widget to examples

Resolves #789

### CODE REVIEW

**Comment by tomdye** [comment]
@samenz could you update this PR to use the theme composition approach from https://github.com/dojo/widgets/pull/855 please?

**Comment by samenz** [comment]
@tomdye updated email input to have the new theme middleware

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-7zyfs0kd4.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-32x6lms21.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-3w87g84wl.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-4u0fmcnki.now.sh

**Pull request merged**
