### PR TITLE
added 'watchForAsyncResult' function to make testing async functions …

### LINKED ISSUE #5: setTimeout in test cases
The only way currently we are able to easily test certain async processes in widgets is using setTimeout.  Obviously this is fragile and should be fixed.

### PR DESCRIPTION
**Pull request by vansimke**
**Type:** bug

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

The current test suite for this repository relies heavily on testing the results of asynchronous actions that don't return promises or offer any other simple method for knowing when the results are ready to be checked. This has led to the heavy use of the setTimeout function with an arbitrary timeout value set. The challenge with this is that values that are too small can cause false failures to be thrown (especially on slow continuous integration machines) or the suite to take too long to complete, if the value is set too high.

This PR adds a wrapper for the setTimeout function that allows a test to be provided that can be used to trigger whether the callback (presumably holding the assertions) will be called or not.

Resolves #5

### CODE REVIEW

**Comment by agubler** [comment]
Hey @vansimke there are some linting errors that meant the tests didn't run on CI

**Comment by vansimke** [comment]
Thanks @agubler, I've fixed it and pushed another commit. There are more tests converted in this version. Hope I'm on the right track ;)

**Comment by matt-gadd** [comment]
@vansimke it would be nice if `watchForAsyncResult` just returned a promise rather than relying on the `dfd` callback (which I consider mostly legacy). 

seen as though the test function is likely most of the time going to be an assertion essentially anyway, is there any reason we can't just attempt the assertion block?

**Comment by agubler** [comment]
indeed it would be nice to just deal in promises for something like this and potentially be able to configure the time between each step.

Also feels like after moving to promises it could just go into core#timing perhaps?

**Comment by matt-gadd** [comment]
And I still think in an ideal world we'd actually be able to control ticks manually via a Promise stub or similar, rather than having to poll.

**Comment by agubler** [comment]
@vansimke this has a few (lots) of conflicts now and I think needs some love :) Also some feedback still outstanding.

**Comment by matt-gadd** [comment]
I think at this point widgets has changed so significantly that this might not be needed, or if so is beyond the realm of conflict fixing.

**Pull request closed without merging**
