### PR TITLE
Run CI functional tests on chrome only

### LINKED ISSUE #487: Restrict intern tests to run in Chrome / Node only
**Enhancement** 

Functional tests are taking 25 minutes plus to run across browserStack right now which is killing productivity and hindering changes. Most of the time failures are down to timeouts / hosting errors and / or differences in browser drivers. 
Our unit tests are pretty comprehensive and widget-core is fully tested already so this should be pretty low risk.
We should restrict test environment to Chrome only. We can look into running scheduled smoke tests against a wider browser stack at a later date.

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Limit functional test running to chrome only via browserstack

Resolves #487

### CODE REVIEW

**Comment by devpaul** [comment]
Can we add an issue to create a nightly cron to functionally test against all browsers in the browser matrix?

**Comment by devpaul** [comment]
Would you add a configuration that allows browser stack and saucelabs to tests against the full browser matrix? i.e.

```json
"configs": {
	"browserstack-all": {
		"extends": "browserstack",
		"environments": [
			{ "browserName": "internet explorer", "version": "11" },
			{ "browserName": "chrome", "os": "Windows", "os_version": "10" }
			{ "browserName": "edge" },
			{ "browserName": "firefox", "os": "Windows", "os_version": "10" },
			{ "browserName": "safari", "version": "9.1", "platform": "MAC" },
			{ "browserName": "iPhone", "version": "9.1" }
 		]
	}
}
```

**Comment by tomdye** [comment]
Fair one @devpaul . Ideally we could ditch browserstack entirely for PR builds and test against the travis chrome headless

**Comment by devpaul** [comment]
I agree wholeheartedly with this change. Test taking more than 10 minutes to run are an issue. I just want us to keep the ability to run against all browsers in browserstack as a manual option so devs can run `dojo test -a -c browserstack-all`. Should be good once we can do that 👍

**Pull request merged**
