### PR TITLE
change outlined to functional, compose themed classes

### PR DESCRIPTION
**Pull request by aciccarello**
Similar to #855 but for outlined button. Still needs to be tested with themes (WIP).

Linked to: #847

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-d3s9ownw7.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-rwxnuic6r.now.sh

**Comment by tomdye** [comment]
@aciccarello is this ready to be merged?

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-5pvdlphol.now.sh
* Tests Deployment: https://dojowidgets-jxse4jmfk.now.sh

**Comment by aciccarello** [comment]
@tomdye I've updated this to add examples and manually tested.

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-9wsxavrx7.now.sh
* Tests Deployment: https://dojowidgets-h6sxsr4cw.now.sh

**Pull request merged**
