### PR TITLE
add zh-CN bundle

### LINKED ISSUE #1503: Add zh-CN language bundles
Add zh-CN language bundles to dojo widgets that use i18n

### PR DESCRIPTION
**Pull request by xiaohulu**
**Type:** bug / feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [ ] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] For new widgets, `theme.variant()` is added to the root domnode
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:**

Add `zh-CN` and `zh-TW`  bundles.

Resolves #1503

### CODE REVIEW

**Comment by tomdye** [comment]
Thanks for doing this @xiaohulu :)

**Comment by xiaohulu** [comment]
@tomdye My pleasure :)

But codecov check failed.

**Comment by tomdye** [comment]
not a problem re. code cov, we should probably exclude the language bundles anyway. I asked you a question on discord re. changing the locale name from `zh-cn` to `zh` so that it covers a wider range of chinese locales. Would that be possible or is the translation you created only valid for `zh-cn` and not for the wider `zh` ?

**Comment by xiaohulu** [comment]
@tomdye `zh-cn` for Simplified Chinese, `zh-tw` for Traditional Chinese.

for example https://github.com/ant-design/ant-design/tree/master/components/locale

image

**Comment by tomdye** [comment]
Thank you for your work on this @xiaohulu, we came across a quirk of cldr data resolution when looking into this for you. It seems that although the lang is `zh-CN`, the locale bundle needs to be specified as `zh`. I have updated this for you and changed the package-lock file to point to a fix we've made in `webpack-contrib`. This should now work with `zh-TW` as desired. Really appreciate your contribution

**Pull request merged**
