### PR TITLE
Update @dojo/core to alpha.26

### PR DESCRIPTION
**Pull request by mwistrand**
**Type:** feature

The following has been addressed in the PR:

* [ ] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Updates `@dojo/core` to alpha.26 to avoid "unmet peer dependency" errors on install.

### CODE REVIEW

**Comment by agubler** [comment]
Can you optimistically update widget-core and i18n too please?

**Comment by agubler** [comment]
@dylans this cannot go in until @mwistrand the other dependencies have been optimistically updated to the next released version.

**Comment by mwistrand** [comment]
`@dojo/i18n` has been released, so I've updated that package version. I also updated the `widget-core` version though that hasn't been released yet.

**Comment by mwistrand** [comment]
`widget-core` is actually updating to alpha.28, which also includes changes to how web components are created (`widgetFactory` => `widgetConstructor`). I made any necessary updates, and once CI passes I'll merge.

**Pull request merged**
