### PR TITLE
SlidePane and Dialog updates and conversion to Classes

### PR DESCRIPTION
**Pull request by tomdye**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**
- Make use of `null` classes functionality
- Drop `-attr` usage
- Add Enum for `Align`
- Add const for min-width
- renamed to slidePane
- dropped camelCase from folder name

Converts both slidepane and dialog to use `Classes`

**Requires**
- Widget-core release
- Conversion to `Classes`

### CODE REVIEW

**Comment by tomdye** [comment]
Apologies to all for the diffing of `createSlidePane.ts`, GH doesn't seem to be happy with it being changed, renamed and moved into a new directory.

**Comment by tomdye** [comment]
@bitpshr have pulled your changes into this PR.

**Comment by bitpshr** [comment]
@tomdye I think we need to bump the widget-core version so the CI will pass, then hopefully we can land this.

**Comment by bitpshr** [comment]
Not sure why this one line isn't covered despite being hit 15 times: https://codecov.io/gh/dojo/widgets/compare/023ecfe575368ecbdfbabf6163f0f77545362085...c28cf622ef916b5ec451f16a46c7e94c6661bf18/diff#D19-47.

**Pull request merged**
