### PR TITLE
Combobox: update unit tests to use test-extras

### LINKED ISSUE #137: ComboBox: Update Unit Tests
Update ComboBox unit tests to use `test-extras`.

### PR DESCRIPTION
**Pull request by msssk**
**Type:** enhancement

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

Resolves #137

### CODE REVIEW

**Comment by agubler** [comment]
@msssk Needs a rebase to for the latest `beta1` release of `widget-core` and `test-extras`.

Also a conflict to resolve.

**Comment by msssk** [comment]
@lzhoucs This one is ready for you to take over - it's incomplete, you'll notice numerous compile errors that need fixing, and then test coverage needs to be improved.

**Comment by lzhoucs** [comment]
It seems two unrelated tests are failing on IE11 that causes the build to fail.

**Comment by lzhoucs** [comment]
It seems the latest master build was also failing on the same test errors: https://travis-ci.org/dojo/widgets/builds/238432970, which also shows the build failure is unrelated to the changes in this PR.

**Comment by pottedmeat** [comment]
Moved to https://github.com/dojo/widgets/pull/312

**Pull request closed without merging**
