### PR TITLE
Add `Label` functional tests.

### LINKED ISSUE #153: Label: Add Functional Tests

### PR DESCRIPTION
**Pull request by lzhoucs**
**Type:** functional tests

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

Resolves #153

### CODE REVIEW

**Comment by lzhoucs** [comment]
@tomdye , I am trying to address your `css-module` feedback using the approach that I used in other PRs: https://github.com/dojo/widgets/pull/168/commits/e426a7f1bf015459aad6626cd5e54637d20764ae, https://github.com/dojo/widgets/pull/170/commits/f6a611bcfcb7195978c73e01bce849b2fef9a7ba. But I ran into an issue. Unlike other widgets, `Label` widget root element doesn't have a `css.root` class, it takes a `classes` property instead, but the containing widget, in my case the example App widget, has to extend `ThemeableMixin` in order to pass this property  to a `Label` instance through `this.classes()`. So if tag name `label` can't be used, do you have any suggestion on how to locate the `Label` widget root element?

**Comment by smhigley** [comment]
@lzhoucs @tomdye I was actually planning on changing Label and removing the `classes` property in favor of form widgets overriding the label class with `extraClasses`. I had wanted to wait until activity around those widgets died down it little, but it seems like it's needed now. I can add a PR for it by EOD today.

**Comment by msssk** [comment]
@smhigley migrating to `extraClasses` is underway:
https://github.com/dojo/widgets/pull/167/files

**Comment by smhigley** [comment]
@msssk nice 👍. In that case, maybe this PR should wait for yours?

**Comment by pottedmeat** [comment]
Moved to https://github.com/dojo/widgets/pull/321

**Pull request closed without merging**
