### PR TITLE
fix: rename CardProperties.onAction to onContentClick

### LINKED ISSUE #1648: Card widget onAction is confusing
Card's `onAction` callback is really just an `onClick` handler for the entire card. This should either be removed or renamed.

### PR DESCRIPTION
**Pull request by bitpshr**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] For new widgets, `theme.variant()` is added to the root domnode
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

This pull request renames the `Card` prop `onAction` to `onContentClick`, since it more-accurately describes what the prop actually does.

Resolves #1648

### CODE REVIEW

**Comment by tomdye** [comment]
I didn't even know there was a click handler for card content. As there aren't any more click handlers for the `Card`, do you think `onClick` would be more appropriate name wise? I think that was the suggestion in the issue too.

**Comment by bitpshr** [comment]
@tomdye `onClick` seems wrong since this does not include the card header, which I'd expect as a consumer. I think we should either call it `onContentClick`, or remove it altogether.

**Comment by bitpshr** [comment]
This pull request has been updated in the following ways:

1. `onClick` is used instead of `onContentClick`, and this applies to all content but the action buttons as per the Material guidelines. See Action Area 1 in [this image](https://lh3.googleusercontent.com/t6XT_g7O4FhNRAK-IhjO4C3yTaSOKbROxr-lamFv6GGE0fh0UJGv36QZ3nQixaZ-OM9jkP0KZFN36ubXIDHjFxOYQuP0IyOW-YGNzzk=w1064-v0) ([reference](https://material.io/components/cards#actions).)
1. Styling was improved for `header` content so it has proper padding.

**Comment by tomdye** [comment]
@bitpshr could you add an example using the click handler please and add the `pointer: cursor` css class we discussed in the dojo call when an `onClick` callback as been passed.

**Review by matt-gadd — APPROVED** [review]

**Review by tomdye — APPROVED** [review]

**Pull request merged**
