### PR TITLE
Issue 1142

### LINKED ISSUE #1142: Change TimePicker to use `Select` and convert to function based
Combobox is being deleted so timepicker should be updated to use the new approach with select and menu.

- convert to function based
- use icache
- accept initialValue
- use select
- remove combobox usage

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:**

> Time picker, picker,
> You picked me at the right time.
> I will rewrite you. ❤️ 

Converting time picker to a functional widget and making it work sort of like date input.  Note that this also includes material styles.

Resolves #1142 #1066 

image

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-q2ulflrw2.now.sh
* Tests Deployment: https://dojowidgets-8rxsrxwph.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-q2ulflrw2.now.sh
* Tests Deployment: https://dojowidgets-967x9zyfi.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-lvf9mdqed.now.sh
* Tests Deployment: https://dojowidgets-87jcb1gch.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-huy4rzq24.now.sh
* Tests Deployment: https://dojowidgets-d55fredgn.now.sh

**Comment by rorticus** [comment]
An excellent point @tomdye 😂 

Fixed!

image

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* Docs Deployment: https://dojowidgets-5p5hxtcgv.now.sh
* Tests Deployment: https://dojowidgets-kio0yrmnt.now.sh

**Pull request merged**
