### PR TITLE
add text-input autocomplete hook

### LINKED ISSUE #1610: Autocomplete messes with floating label styles like those in Material
**Bug** 

Screenshot 2020-12-07 at 13 34 52

Apparently this can be fixed with a transition to trigger js via the ` :-webkit-autofill` pseudo (e.g https://codedaily.io/tutorials/69/Animated-Input-Label-with-Chrome-Autofill-Detection-in-React).

### PR DESCRIPTION
**Pull request by aciccarello**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] For new widgets, `theme.variant()` is added to the root domnode
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:**
Use keyframes to trigger an event when 

Resolves #1610

### CODE REVIEW

**Review by tomdye — APPROVED** [review]
Looks good to me, do you think it should also call `onValue` when the input is autocompleted?

**Comment by aciccarello** [comment]
Good question @tomdye. I think that would make sense to add.

**Comment by aciccarello** [comment]
@tomdye I remembered that the value isn't available at this point (for security reasons) so there wouldn't be any value to pass in the callback

**Comment by tomdye** [comment]
@aciccarello fair enough re. value not being available. I recall a similar issue with autocomplete on a sign in form needing to enable a sign in button. This PR is already approved.

**Pull request merged**
