### PR TITLE
update interface of title-pane

### PR DESCRIPTION
**Pull request by nka089**
Interface changed, so that users can style the property independently

**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [ ] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Resolves #878

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-p0aykbfsj.now.sh

**Comment by tomdye** [comment]
@nka089 thanks for raising this pull request. We encourage our users to contribute towards Dojo but we would ask that they take a look at the [contributing guidelines](https://github.com/dojo/meta/blob/master/CONTRIBUTING.md) and follow our process which includes first raising an issue for discussion with the core dojo team. Once the issue has been raised, verified and refined, a pull request with appropriate tests can be raised.

**Comment by nka089** [comment]
@tomdye Hi Tom, I added some tests

**Comment by dojo-site** [comment]
This pull request has been deployed to:

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-gt8vge8pb.now.sh

**Pull request merged**
