### PR TITLE
Codesandbox CI

### PR DESCRIPTION
**Pull request by agubler**

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-3wt984wwu.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-cvju5pc0s.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-ktshojpxa.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.widgets: https://dojowidgets-4j7a47ekd.now.sh

**Comment by tomdye** [comment]
@agubler is this good to go once the conflicts are fixed?

**Pull request closed without merging**
