### PR TITLE
Add disabled to CheckboxGroup and RadioGroup

### LINKED ISSUE #1698: Checkbox/Radiobox group missing disabled property
**Enhancement**

At present, checkbox and radiobox group widgets do not have a `disabled` property.
We should add a top level `disabled?: boolean` property that can be used to disable all inputs within the group.

### PR DESCRIPTION
**Pull request by samends**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] For new widgets, `theme.variant()` is added to the root domnode
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**
- Adds `disabled` field to `RadioGroup` `options` property
- - Adds `disabled` field to `CheckboxGroup` `options` property

Resolves #1698

### CODE REVIEW

**Comment by tomdye** [comment]
@samends , Im not sure this does what the ticket referred to which was a top level `disabled` property to disable all checkboxes / radios in a group.
> We should add a top level disabled?: boolean property that can be used to disable all inputs within the group.

**Comment by samends** [comment]
@tomdye should we keep the individual disable property? I can also add a top level disable

**Comment by agubler** [comment]
@tomdye @samends I think this should be just a top level disable, for more complex functionality users can implement their own custom renderer.

**Comment by agubler** [comment]
Superseded by #1745

**Pull request closed without merging**
