### PR TITLE
Focused class on form widgets

### PR DESCRIPTION
**Pull request by smhigley**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Adds a `css.focused` class to the root node of form widgets when the widget contains focus. This makes it possible to make the styling change referenced in #458

### CODE REVIEW

**Comment by tomdye** [comment]
@smhigley do you think that `focus` property should be passed to the `label` as well?

**Comment by smhigley** [comment]
@tomdye I would lean towards not providing that to `Label`. Generally the focus outline/highlight should stick pretty close to the actual thing in focus, and I'm having a hard time thinking of a good use case for the label styles needing to change when the input is focused.

**Comment by smhigley** [comment]
I actually think it makes more DOM sense to have the `.focused` class on `.inputWrapper` in most cases, but organizationally we already have `getModifierClasses` and some widgets like `Listbox` lack `inputWrapper`.

**Comment by tomdye** [comment]
@smhigley I understand what you're saying re. label, however, I am thinking about scenarios such as the floating labels for material input labels. Without the ability to set the label as `focused`, I believe you would find it harder to add the appropriate effect via a theme.

screenshot 2018-02-15 10 08 02

**Pull request merged**
