### PR TITLE
Remove showcase

### PR DESCRIPTION
**Pull request by umaar**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Remove the grunt deploy config for the showcase page

Works towards: https://github.com/dojo/examples/issues/248

### CODE REVIEW

**Comment by umaar** [comment]
Any idea about the failing build which says: `× safari 9.1 on iOS 9.1 - TextInput - Validated TextInput should update style based on validity (2.127s)
` I don't think that's related?

**Comment by umaar** [comment]
Thanks @bitpshr! I removed `grunt-exec` and `grunt-prompt`, I guess the others are used:

image

Do you think we're good to merge?

**Comment by umaar** [comment]
Also can I merge even the build is failing with errors like `× firefox on windows_nt 6.3 - TextInput - TextInput should gain focus when clicking on the label (6.329s)`?

**Comment by bitpshr** [comment]
Yes, I think this is good to merge @umaar. The test failures were not caused by this work.

**Comment by tomdye** [comment]
Just conflicts to remove @umaar

**Comment by bitpshr** [comment]
Closing in favor of #344.

**Pull request closed without merging**
